"""empty message

Revision ID: 34a4af736122
Revises: 
Create Date: 2024-06-25 15:00:06.955962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34a4af736122'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_username'), ['username'], unique=True)

    op.create_table('accounts_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin', sa.Double(), nullable=True),
    sa.Column('current_mouse_id', sa.Integer(), nullable=True),
    sa.Column('current_video_card_id', sa.Integer(), nullable=True),
    sa.Column('tired', sa.Integer(), nullable=True),
    sa.Column('have_bot', sa.Boolean(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mouses_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('mine_value', sa.Double(), nullable=True),
    sa.Column('require_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_cards_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('mine_value', sa.Double(), nullable=True),
    sa.Column('require_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('mine_value', sa.Double(), nullable=True),
    sa.Column('require_level', sa.Integer(), nullable=True),
    sa.Column('account_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_data_id'], ['accounts_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('mine_value', sa.Double(), nullable=True),
    sa.Column('require_level', sa.Integer(), nullable=True),
    sa.Column('account_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_data_id'], ['accounts_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_cards')
    op.drop_table('mouses')
    op.drop_table('video_cards_base')
    op.drop_table('mouses_base')
    op.drop_table('accounts_data')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_username'))
        batch_op.drop_index(batch_op.f('ix_accounts_timestamp'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
