"""empty message

Revision ID: ab01726eb375
Revises: 34a4af736122
Create Date: 2024-07-27 20:31:58.135378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab01726eb375'
down_revision = '34a4af736122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mouses_base')
    op.drop_table('video_cards')
    op.drop_table('video_cards_base')
    op.drop_table('mouses')
    with op.batch_alter_table('accounts_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fio', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.String(), nullable=True))
        batch_op.drop_column('coin')
        batch_op.drop_column('have_bot')
        batch_op.drop_column('tired')
        batch_op.drop_column('current_mouse_id')
        batch_op.drop_column('current_video_card_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_video_card_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('current_mouse_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('tired', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('have_bot', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('coin', sa.DOUBLE(), nullable=True))
        batch_op.drop_column('date')
        batch_op.drop_column('phone')
        batch_op.drop_column('fio')

    op.create_table('mouses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('mine_value', sa.DOUBLE(), nullable=True),
    sa.Column('require_level', sa.INTEGER(), nullable=True),
    sa.Column('account_data_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['account_data_id'], ['accounts_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_cards_base',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('mine_value', sa.DOUBLE(), nullable=True),
    sa.Column('require_level', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_cards',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('mine_value', sa.DOUBLE(), nullable=True),
    sa.Column('require_level', sa.INTEGER(), nullable=True),
    sa.Column('account_data_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['account_data_id'], ['accounts_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mouses_base',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('mine_value', sa.DOUBLE(), nullable=True),
    sa.Column('require_level', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
